# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/mark/fpga/src/zcu106/pcie_led_ex_design/pcie4_uscale_plus_0_ex/imports/xilinx_pcie4_uscale_plus_x0y0.xdc

# IP: ip/pcie4_uscale_plus_0/pcie4_uscale_plus_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pcie4_uscale_plus_0 || ORIG_REF_NAME==pcie4_uscale_plus_0} -quiet] -quiet
